---
kind: pipeline
name: default

steps:
  - name: Run rspec
    image: ruby:2.6
    commands:
      - gem install bundler:2.0.2
      - bundle install --jobs=$(nproc) --retry=3 --path vendor/bundle
      - bundle exec rspec

trigger:
  event:
    - push
